export type Level = 'Básica Superior' | 'Bachillerato';
export type CourseName = '8 EGB A' | '8 EGB B' | '9 EGB A' | '9 EGB B' | '10 EGB A' | '10 EGB B' | '1 BACH. A' | '1 BACH. B' | '2 BACH. A' | '2 BACH. B' | '3 BACH. A' | '3 BACH. B';
export type SubjectName = 'Matemáticas' | 'Lengua y Literatura' | 'Ciencias Naturales' | 'Biología' | 'Química' | 'Física' | 'Diplomado' | 'Indagación' | 'Filosofía' | 'Patrimonio' | 'Ciudadanía' | 'Ciencias Sociales' | 'Investigación' | 'Estudios Sociales';

export const STUDENTS_DATA = [
  // 3 BACH. B
  { code: '03313', name: 'BASTIDAS ULLAURI ANTONELLA SOLEDAD', course: '3 BACH. B', level: 'Bachillerato' },
  { code: '03712', name: 'BERMEO BUESTAN PABLO ANDRES', course: '3 BACH. B', level: 'Bachillerato' },
  { code: '02244', name: 'BERMEO CEVALLOS JOSUE SANTIAGO', course: '3 BACH. B', level: 'Bachillerato' },
  { code: '02214', name: 'CABRERA SERRANO JULIANA', course: '3 BACH. B', level: 'Bachillerato' },
  { code: '02822', name: 'CARPIO SOLIS RUTH IRENE', course: '3 BACH. B', level: 'Bachillerato' },
  { code: '02821', name: 'CARPIO SOLIS IVAN JOEL', course: '3 BACH. B', level: 'Bachillerato' },
  { code: '03389', name: 'CORONEL URDIALEZ CESAR PAUL', course: '3 BACH. B', level: 'Bachillerato' },
  { code: '02220', name: 'ENCALADA CEDILLO CRISTIAN DAVID', course: '3 BACH. B', level: 'Bachillerato' },
  { code: '02402', name: 'FLORES ESTEVEZ JUAN FRANCISCO', course: '3 BACH. B', level: 'Bachillerato' },
  { code: '02819', name: 'FUENTES BRAVO JEREMY IAHEL', course: '3 BACH. B', level: 'Bachillerato' },
  { code: '03433', name: 'GAVILANEZ BUSTOS APOLO GABRIEL', course: '3 BACH. B', level: 'Bachillerato' },
  { code: '02259', name: 'HUAZHCO HURTADO MARIA EDUARDA', course: '3 BACH. B', level: 'Bachillerato' },
  { code: '02227', name: 'MALLA PATIÑO CAMILA DANIELA', course: '3 BACH. B', level: 'Bachillerato' },
  { code: '03338', name: 'MOSCOSO HURTADO MARTINA ISABEL', course: '3 BACH. B', level: 'Bachillerato' },
  { code: '03185', name: 'PAREDES VEJAR LUCIANO JOAQUIN', course: '3 BACH. B', level: 'Bachillerato' },
  { code: '02242', name: 'PARRA MUÑOZ VICTORIA VALENTINA', course: '3 BACH. B', level: 'Bachillerato' },
  { code: '02225', name: 'SALAMEA VASQUEZ PEDRO ANDRES', course: '3 BACH. B', level: 'Bachillerato' },
  { code: '02241', name: 'SALGADO MOGROVEJO NICOLAS ANDRES', course: '3 BACH. B', level: 'Bachillerato' },
  { code: '02236', name: 'SANCHEZ GUTIERREZ CRISTIAN AUGUSTO', course: '3 BACH. B', level: 'Bachillerato' },
  { code: '03594', name: 'SERRANO CONTRERAS JOAQUIN GUSTAVO', course: '3 BACH. B', level: 'Bachillerato' },
  { code: '02240', name: 'SILVA GUERRERO MAITE MARIELA', course: '3 BACH. B', level: 'Bachillerato' },
  { code: '02967', name: 'ZALAMEA BURGUEÑO JOSEFA', course: '3 BACH. B', level: 'Bachillerato' },
  
  // 3 BACH. A
  { code: '03336', name: 'ABRIL ESPINOSA NELSON NICOLAS', course: '3 BACH. A', level: 'Bachillerato' },
  { code: '02231', name: 'ALVARADO TORAL JUAN JOSE', course: '3 BACH. A', level: 'Bachillerato' },
  { code: '03676', name: 'BERMEJO GOMEZ CHRISTOPHER ALEXANDER', course: '3 BACH. A', level: 'Bachillerato' },
  { code: '02825', name: 'CAJAS PILLACELA ISAAC ANDRES', course: '3 BACH. A', level: 'Bachillerato' },
  { code: '03667', name: 'CAMPOVERDE GONZALEZ LUIS EDUARDO', course: '3 BACH. A', level: 'Bachillerato' },
  { code: '03254', name: 'CEDILLO PIEDRA RENATA VALENTINA', course: '3 BACH. A', level: 'Bachillerato' },
  { code: '02829', name: 'CEVALLOS CELLERI ISABELLA ANAHI', course: '3 BACH. A', level: 'Bachillerato' },
  { code: '02245', name: 'COELLAR MORA MARTIN ALEXANDER', course: '3 BACH. A', level: 'Bachillerato' },
  { code: '03621', name: 'GUZÑAY SERRANO NICOLAS XAVIER', course: '3 BACH. A', level: 'Bachillerato' },
  { code: '02828', name: 'LÓPEZ FREIRE RAFAELA ISABEL', course: '3 BACH. A', level: 'Bachillerato' },
  { code: '02549', name: 'MENESES QUEZADA MADISON ANGELINE', course: '3 BACH. A', level: 'Bachillerato' },
  { code: '03627', name: 'ORTEGA AMBROSI INTIEL', course: '3 BACH. A', level: 'Bachillerato' },
  { code: '02310', name: 'ORTIZ BRITO JAVIER RAFAEL', course: '3 BACH. A', level: 'Bachillerato' },
  { code: '02499', name: 'ORTIZ JUAREZ ALFREDO SEBASTIAN', course: '3 BACH. A', level: 'Bachillerato' },
  { code: '02872', name: 'PALACIOS CASTRO CAMILA DOMÉNICA', course: '3 BACH. A', level: 'Bachillerato' },
  { code: '03726', name: 'PAVON PEÑA ANIBL SEBASTIAN', course: '3 BACH. A', level: 'Bachillerato' },
  { code: '03439', name: 'PAZAN TOLEDO WALTER ALEJANDRO', course: '3 BACH. A', level: 'Bachillerato' },
  { code: '02558', name: 'PEREZ SIGCHA MARIA JULIANA', course: '3 BACH. A', level: 'Bachillerato' },
  { code: '03668', name: 'SALAMEA TACURI DIEGO NICOLAS', course: '3 BACH. A', level: 'Bachillerato' },
  { code: '02824', name: 'TORRES GONZÁLEZ MARLON JEHOSAFAT', course: '3 BACH. A', level: 'Bachillerato' },
  { code: '02274', name: 'ULLOA ZEAS VICTORIA EMILIA', course: '3 BACH. A', level: 'Bachillerato' },
  { code: '03029', name: 'ZAMORA RODAL DANIEL ALEJANDRO', course: '3 BACH. A', level: 'Bachillerato' },

  // 2 BACH. B
  { code: '03717', name: 'ARICHAVALA JARA JUAN ANDRES', course: '2 BACH. B', level: 'Bachillerato' },
  { code: '03163', name: 'BARRERA RAMON DOMINIQUE NICOLAS', course: '2 BACH. B', level: 'Bachillerato' },
  { code: '02340', name: 'CARDENAS RODAS DANNA AMELIA', course: '2 BACH. B', level: 'Bachillerato' },
  { code: '03162', name: 'CARPIO CASTRO MARIA AMELIA', course: '2 BACH. B', level: 'Bachillerato' },
  { code: '03331', name: 'CARPIO GUILLEN MARCELO SEBASTIAN', course: '2 BACH. B', level: 'Bachillerato' },
  { code: '03731', name: 'CHACON PESANTEZ JAEL VALENTINA', course: '2 BACH. B', level: 'Bachillerato' },
  { code: '03435', name: 'CRIOLLO SAMANIEGO ELIAS ISMAEL', course: '2 BACH. B', level: 'Bachillerato' },
  { code: '02322', name: 'DURAZNO SHININ LUCIANA ISABELLA', course: '2 BACH. B', level: 'Bachillerato' },
  { code: '03750', name: 'FLORES GUAMAN JOAQUIN ENRIQUE', course: '2 BACH. B', level: 'Bachillerato' },
  { code: '03453', name: 'FLORES VALLEJO JULIANA SOFIA', course: '2 BACH. B', level: 'Bachillerato' },
  { code: '02332', name: 'LAZO SALAZAR SOFIA VALENTINA', course: '2 BACH. B', level: 'Bachillerato' },
  { code: '02639', name: 'MONTALEZA ABAD LYLA ANALIZ', course: '2 BACH. B', level: 'Bachillerato' },
  { code: '03328', name: 'MONTAÑA BARBA ALVARO', course: '2 BACH. B', level: 'Bachillerato' },
  { code: '03386', name: 'MOROCHO JIMENEZ ESTEBAN JOSE', course: '2 BACH. B', level: 'Bachillerato' },
  { code: '03327', name: 'REYES DAVILA JULIAN SAUL', course: '2 BACH. B', level: 'Bachillerato' },
  { code: '02352', name: 'ROJAS ALVARADO JUAN FRANCISCO', course: '2 BACH. B', level: 'Bachillerato' },
  { code: '03240', name: 'TORRES MINUCHE JUAN CARLOS', course: '2 BACH. B', level: 'Bachillerato' },
  { code: '02806', name: 'TOSI TELLO JULIANA FRANCESCA', course: '2 BACH. B', level: 'Bachillerato' },

  // 2 BACH. A
  { code: '02334', name: 'CAMPO RAMIREZ JUAN DANIEL', course: '2 BACH. A', level: 'Bachillerato' },
  { code: '02782', name: 'CAMPOVERDE CASTRO MARÍA VICTORIA', course: '2 BACH. A', level: 'Bachillerato' },
  { code: '02360', name: 'CEDILLO ORDOÑEZ MELISSA ALEXANDRA', course: '2 BACH. A', level: 'Bachillerato' },
  { code: '02358', name: 'GALINDO ALEMAN SAMMAY', course: '2 BACH. A', level: 'Bachillerato' },
  { code: '02325', name: 'HIDROBO FAJARDO IVAN SEBASTIAN', course: '2 BACH. A', level: 'Bachillerato' },
  { code: '02336', name: 'IDROVO CABRERA SOFIA MICAELA', course: '2 BACH. A', level: 'Bachillerato' },
  { code: '03219', name: 'MERCHAN GUILLEN JAVIER ALEXANDER', course: '2 BACH. A', level: 'Bachillerato' },
  { code: '03487', name: 'NOLASCO JARAMILLO KAMILLY LORAINE', course: '2 BACH. A', level: 'Bachillerato' },
  { code: '02349', name: 'OCHOA HIDALGO RAFAEL', course: '2 BACH. A', level: 'Bachillerato' },
  { code: '02338', name: 'ORMAZA PESÁNTEZ DIEGO ALEJANDRO', course: '2 BACH. A', level: 'Bachillerato' },
  { code: '03548', name: 'PINEDA JARA ISABELLA ESTEFANIA', course: '2 BACH. A', level: 'Bachillerato' },
  { code: '03542', name: 'PONCE MORALES JOSE MARTIN', course: '2 BACH. A', level: 'Bachillerato' },
  { code: '03485', name: 'RINCONES MOLINA VICTORIA DEL CARMEN', course: '2 BACH. A', level: 'Bachillerato' },
  { code: '02646', name: 'SANCHEZ SARMIENTO MARLON DAVID', course: '2 BACH. A', level: 'Bachillerato' },
  { code: '02817', name: 'SINCHI ORDOÑEZ ANGELA STEFANI', course: '2 BACH. A', level: 'Bachillerato' },
  { code: '02351', name: 'VASQUEZ JARAMILLO MARTINA SOFIA', course: '2 BACH. A', level: 'Bachillerato' },
  { code: '03578', name: 'ZEAS ZUÑIGA ISABELLA VALENTINA', course: '2 BACH. A', level: 'Bachillerato' },

  // 1 BACH. B
  { code: '02529', name: 'ALVAREZ GUILLEN BRUNO NICOLAS', course: '1 BACH. B', level: 'Bachillerato' },
  { code: '03197', name: 'ALVAREZ VILLAVICENCIO JOAQUIN ESTEBAN', course: '1 BACH. B', level: 'Bachillerato' },
  { code: '02969', name: 'ASTUDILLO QUEZADA MARIA PAZ', course: '1 BACH. B', level: 'Bachillerato' },
  { code: '02450', name: 'BRAVO GALARZA MARLA SOFIA', course: '1 BACH. B', level: 'Bachillerato' },
  { code: '03656', name: 'BUCHELI MALDONADO JOAQUIN', course: '1 BACH. B', level: 'Bachillerato' },
  { code: '02497', name: 'CARRION DUERTO LUCAS AGUSTIN', course: '1 BACH. B', level: 'Bachillerato' },
  { code: '03730', name: 'CHACON PESANTEZ MONICA DANIELA', course: '1 BACH. B', level: 'Bachillerato' },
  { code: '02482', name: 'CHAPARRO GUAMÁN MARTIN ESTEBAN', course: '1 BACH. B', level: 'Bachillerato' },
  { code: '02637', name: 'CHIRIBOGA ABAD LINDA XAVIERA', course: '1 BACH. B', level: 'Bachillerato' },
  { code: '03710', name: 'CHUQUI RAMON RAFAELA VALENTINA', course: '1 BACH. B', level: 'Bachillerato' },
  { code: '03713', name: 'CUEVA VEGA BRUNO NAHUEL', course: '1 BACH. B', level: 'Bachillerato' },
  { code: '02467', name: 'DELEG ABRIL JOSE EDUARDO', course: '1 BACH. B', level: 'Bachillerato' },
  { code: '02454', name: 'GONZÁLEZ VÉLEZ CAMILA VICTORIA', course: '1 BACH. B', level: 'Bachillerato' },
  { code: '02781', name: 'HARDY NICHOLAS MERRITT', course: '1 BACH. B', level: 'Bachillerato' },
  { code: '02776', name: 'HIDALGO CRESPO ISABELLA ALEXANDRA', course: '1 BACH. B', level: 'Bachillerato' },
  { code: '02551', name: 'MOLINA PERALVO JOAQUIN', course: '1 BACH. B', level: 'Bachillerato' },
  { code: '03041', name: 'MOSCOSO CASTILLO SEBASTIAN ANDRES', course: '1 BACH. B', level: 'Bachillerato' },
  { code: '02466', name: 'ORELLANA ZAMBRANO MARTIN NICOLAS', course: '1 BACH. B', level: 'Bachillerato' },
  { code: '03366', name: 'PREOBRAZHENSKAIA EKATERINA', course: '1 BACH. B', level: 'Bachillerato' },
  { code: '03184', name: 'PUNIN SAMANIEGO WILLAM DOMINICK', course: '1 BACH. B', level: 'Bachillerato' },
  { code: '02778', name: 'QUINDE GUAMAN PAULINA ALEJANDRA', course: '1 BACH. B', level: 'Bachillerato' },
  { code: '02779', name: 'QUINTEROS ESPINOZA DEREK ALEJANDRO', course: '1 BACH. B', level: 'Bachillerato' },
  { code: '02496', name: 'RODAS BARROS JOSUE ANDRES', course: '1 BACH. B', level: 'Bachillerato' },
  { code: '03357', name: 'RODRIGUEZ LOJA SANDRO EMMANUEL', course: '1 BACH. B', level: 'Bachillerato' },
  { code: '03714', name: 'RODRIGUEZ ORELLANA JUAN MARTIN', course: '1 BACH. B', level: 'Bachillerato' },
  { code: '03607', name: 'SEMINARIO GARCES MICAELA', course: '1 BACH. B', level: 'Bachillerato' },
  { code: '03535', name: 'SIAVICHAY CANCHINGRE MAITE', course: '1 BACH. B', level: 'Bachillerato' },

  // 1 BACH. A
  { code: '03335', name: 'ABRIL ESPINOSA JOAQUIN FRANCISCO', course: '1 BACH. A', level: 'Bachillerato' },
  { code: '02478', name: 'BATALLAS CARPIO CESAR FRANCISCO', course: '1 BACH. A', level: 'Bachillerato' },
  { code: '02445', name: 'BUSTAMANTE SOLORZANO ROMINA', course: '1 BACH. A', level: 'Bachillerato' },
  { code: '02775', name: 'CAJAS PILLACELA JHAQUELINE ABIGAIL', course: '1 BACH. A', level: 'Bachillerato' },
  { code: '02469', name: 'COBOS SORIA JOAQUIN ALEJANDRO', course: '1 BACH. A', level: 'Bachillerato' },
  { code: '02470', name: 'COELLAR MORA LIAM JOSUE', course: '1 BACH. A', level: 'Bachillerato' },
  { code: '03711', name: 'DELGADO TORRES JUAN MARTIN', course: '1 BACH. A', level: 'Bachillerato' },
  { code: '03709', name: 'ENCALADA VERDUGO SANTIAGO ALEJANDRO', course: '1 BACH. A', level: 'Bachillerato' },
  { code: '03441', name: 'ESCANDON MURILLO DANNA MIRELY', course: '1 BACH. A', level: 'Bachillerato' },
  { code: '02510', name: 'FREIRE CONTRERAS PEDRO JOSE', course: '1 BACH. A', level: 'Bachillerato' },
  { code: '02453', name: 'IDROVO BERMEO SOFIA MICAELA', course: '1 BACH. A', level: 'Bachillerato' },
  { code: '02455', name: 'LARREA CARVAJAL PABLO ESTEBAN', course: '1 BACH. A', level: 'Bachillerato' },
  { code: '02447', name: 'LARRIVA GUARACA MATEO ALEJANDRO', course: '1 BACH. A', level: 'Bachillerato' },
  { code: '02772', name: 'MOLINA ÁLVAREZ ISABELA XIMENA', course: '1 BACH. A', level: 'Bachillerato' },
  { code: '02436', name: 'MONTEROS CALDERON NICOLAS EMANUEL', course: '1 BACH. A', level: 'Bachillerato' },
  { code: '02484', name: 'NIETO ORELLANA LAURA ISABELA', course: '1 BACH. A', level: 'Bachillerato' },
  { code: '03380', name: 'ORTEGA GALLEGOS TIFFANY MICHELLE', course: '1 BACH. A', level: 'Bachillerato' },
  { code: '02481', name: 'PERALTA GUILLEN MARIA RAFAELA', course: '1 BACH. A', level: 'Bachillerato' },
  { code: '02433', name: 'PIEDRA CORDERO RENATO JOSÉ', course: '1 BACH. A', level: 'Bachillerato' },
  { code: '03242', name: 'PIEDRA VELIZ AMELIA', course: '1 BACH. A', level: 'Bachillerato' },
  { code: '02473', name: 'SALAMEA VASQUEZ JULIANA', course: '1 BACH. A', level: 'Bachillerato' },
  { code: '02468', name: 'SANCHEZ GUTIERREZ CRISTIAN ALEJANDRO', course: '1 BACH. A', level: 'Bachillerato' },
  { code: '02426', name: 'SERRANO VAN DER BLIEK ALYSA MIKAYLA', course: '1 BACH. A', level: 'Bachillerato' },
  { code: '03728', name: 'SINCHI PAZ ALLAN ISRAEL', course: '1 BACH. A', level: 'Bachillerato' },
  { code: '03732', name: 'SUAREZ CRIOLLO DENNYS DAVID', course: '1 BACH. A', level: 'Bachillerato' },
  { code: '03496', name: 'VELEPUCHA ZHICAY ALEX NICOLAS', course: '1 BACH. A', level: 'Bachillerato' },

  // 9 EGB B
  { code: '02686', name: 'CHABLAY ALVARRACIN ISMAEL FERNANDO', course: '9 EGB B', level: 'Básica Superior' },
  { code: '03628', name: 'GORDILLO MENDOZA ASHLEY FERNANDA', course: '9 EGB B', level: 'Básica Superior' },
  { code: '03390', name: 'JACOME NAVARRETE DEBORA SOFIA', course: '9 EGB B', level: 'Básica Superior' },
  { code: '02755', name: 'LEON RAMON LEONARDO SEBASTIAN', course: '9 EGB B', level: 'Básica Superior' },
  { code: '02687', name: 'MINCHALO GONZALEZ MIA VALENTINA', course: '9 EGB B', level: 'Básica Superior' },
  { code: '02660', name: 'MOLINA POZO RENATA RAFAELA', course: '9 EGB B', level: 'Básica Superior' },
  { code: '02663', name: 'NARVAEZ YUNGASACA EMILIA RAFAELLA', course: '9 EGB B', level: 'Básica Superior' },
  { code: '03381', name: 'ORELLANA MARTINEZ JUAN MANUEL', course: '9 EGB B', level: 'Básica Superior' },
  { code: '02675', name: 'ORELLANA QUINTUÑA JORDAN MIGUEL', course: '9 EGB B', level: 'Básica Superior' },
  { code: '03587', name: 'PEREZ VIMOS DALIA BEATRICE', course: '9 EGB B', level: 'Básica Superior' },
  { code: '02692', name: 'ROBLES TAPIA ANDRES JOAQUIN', course: '9 EGB B', level: 'Básica Superior' },
  { code: '03158', name: 'RONQUILLO BERMEO EDUARDO JOSE', course: '9 EGB B', level: 'Básica Superior' },
  { code: '03342', name: 'SALAMEA LAMULLE MELISSA ISABEL', course: '9 EGB B', level: 'Básica Superior' },
  { code: '02672', name: 'SERRANO VAN DER BLIEK OLIVIER NICOLAS', course: '9 EGB B', level: 'Básica Superior' },
  { code: '02693', name: 'VASQUEZ ALVARRACIN MATEO JOSUE', course: '9 EGB B', level: 'Básica Superior' },
  { code: '02651', name: 'VERDUGO CASTRO EDGAR MARTÍN', course: '9 EGB B', level: 'Básica Superior' },

  // 9 EGB A
  { code: '03705', name: 'AGUILAR BRITO DANIEL AGUSTIN', course: '9 EGB A', level: 'Básica Superior' },
  { code: '02706', name: 'AVILES UREÑA MATIAS FABIAN', course: '9 EGB A', level: 'Básica Superior' },
  { code: '02669', name: 'BERREZUETA BERMEO JUAN ANTONIO', course: '9 EGB A', level: 'Básica Superior' },
  { code: '02682', name: 'CONTRERAS HERAS EMILIO ANDRES', course: '9 EGB A', level: 'Básica Superior' },
  { code: '03483', name: 'COUSSEAU MADRIGAL MARIA EMILIA', course: '9 EGB A', level: 'Básica Superior' },
  { code: '02657', name: 'ENCALADA AVILA SOFIA BELEN', course: '9 EGB A', level: 'Básica Superior' },
  { code: '03675', name: 'FERNANDEZ LEON AIMEE GUADALUPE', course: '9 EGB A', level: 'Básica Superior' },
  { code: '03647', name: 'MONTALVO PUGA SEBASTIAN ALEJANDRO', course: '9 EGB A', level: 'Básica Superior' },
  { code: '03718', name: 'MOSCOSO COBOS MARIA PAZ', course: '9 EGB A', level: 'Básica Superior' },
  { code: '02748', name: 'ORELLANA FAJARDO JEANETH ABIGAIL', course: '9 EGB A', level: 'Básica Superior' },
  { code: '02751', name: 'ORTIZ SALAZAR JENNYFER AILY', course: '9 EGB A', level: 'Básica Superior' },
  { code: '02655', name: 'QUITO GONNET EMMA LUCÍA', course: '9 EGB A', level: 'Básica Superior' },
  { code: '03482', name: 'RAMOS LARRIVA LUNA', course: '9 EGB A', level: 'Básica Superior' },
  { code: '03484', name: 'REISE MASSEILOT JUANA FELICITAS', course: '9 EGB A', level: 'Básica Superior' },
  { code: '02747', name: 'SHIRAISHI CHACON NATALIE YUA', course: '9 EGB A', level: 'Básica Superior' },
  { code: '03606', name: 'VELEZ ALVAREZ MARIEMILIA SVETLANA', course: '9 EGB A', level: 'Básica Superior' },
  { code: '02684', name: 'VERGARA ANGAMARCA ADRIAN MAURICIO', course: '9 EGB A', level: 'Básica Superior' },

  // 10 EGB B
  { code: '03588', name: 'AVILA CABRERA SISA ALEJANDRA', course: '10 EGB B', level: 'Básica Superior' },
  { code: '03704', name: 'BARROS ARIAS NICOLAS BLADIMIR', course: '10 EGB B', level: 'Básica Superior' },
  { code: '03437', name: 'BERNAL ROMERO DANILO BENJAMIN', course: '10 EGB B', level: 'Básica Superior' },
  { code: '02690', name: 'BRAVO QUITO ISAAC FERNANDO', course: '10 EGB B', level: 'Básica Superior' },
  { code: '02566', name: 'CABRERA MORENO SOFIA ALEJANDRA', course: '10 EGB B', level: 'Básica Superior' },
  { code: '02548', name: 'CARRION CORDERO AGUSTINA', course: '10 EGB B', level: 'Básica Superior' },
  { code: '03493', name: 'CASTILLO MALDONADO SOFIA', course: '10 EGB B', level: 'Básica Superior' },
  { code: '02765', name: 'FLORES FIGUEROA FRANCISCO NICANOR', course: '10 EGB B', level: 'Básica Superior' },
  { code: '03359', name: 'GALA DAHILI GABRIELLE ISABELLA', course: '10 EGB B', level: 'Básica Superior' },
  { code: '03571', name: 'GALARZA MARQUEZ MAITANE JOAQUINA', course: '10 EGB B', level: 'Básica Superior' },
  { code: '03582', name: 'GALVEZ CAGUANA DANNA MIKAELA', course: '10 EGB B', level: 'Básica Superior' },
  { code: '03492', name: 'LIMA RIERA NAYELI DAYANNA', course: '10 EGB B', level: 'Básica Superior' },
  { code: '03624', name: 'LOAYZA BERMUDEZ LUCIANA ISABELA', course: '10 EGB B', level: 'Básica Superior' },
  { code: '02584', name: 'MARTINEZ RAMIREZ PEDRO MATIAS', course: '10 EGB B', level: 'Básica Superior' },
  { code: '02550', name: 'MENESES QUEZADA CELIA JULIETH', course: '10 EGB B', level: 'Básica Superior' },
  { code: '02580', name: 'PACHECO ALMACHE ANALIZ VALENTINA', course: '10 EGB B', level: 'Básica Superior' },
  { code: '02814', name: 'PARRA CORDOVA MARIA DE LOS ANGELES', course: '10 EGB B', level: 'Básica Superior' },
  { code: '03708', name: 'PERALTA YEPEZ MATIAS AGUSTIN', course: '10 EGB B', level: 'Básica Superior' },
  { code: '03051', name: 'PRADO ORDOÑEZ EMILIO JOSE', course: '10 EGB B', level: 'Básica Superior' },
  { code: '02761', name: 'RODRÍGUEZ LEÓN DANNA CAROLINA', course: '10 EGB B', level: 'Básica Superior' },
  { code: '02619', name: 'RODRIGUEZ SALAMEA MICHELLE RAFAELA', course: '10 EGB B', level: 'Básica Superior' },
  { code: '02666', name: 'TAPIA BANEGAS ANALIA MONSERRATH', course: '10 EGB B', level: 'Básica Superior' },
  { code: '02759', name: 'VASQUEZ ORDOÑEZ LUCIANO MAURICIO', course: '10 EGB B', level: 'Básica Superior' },
  { code: '02968', name: 'ZALAMEA BURGUEÑO MATÍAS', course: '10 EGB B', level: 'Básica Superior' },

  // 10 EGB A
  { code: '02977', name: 'ALTAMIRANO MANTILLA REBECA ALEJANDRA', course: '10 EGB A', level: 'Básica Superior' },
  { code: '02431', name: 'ANDRADE IDROVO RAFAELA', course: '10 EGB A', level: 'Básica Superior' },
  { code: '03706', name: 'AREVALO CORDOVA ANA ELISA', course: '10 EGB A', level: 'Básica Superior' },
  { code: '03369', name: 'ARIAS GOMEZCOELLO VIOLETA CATALINA', course: '10 EGB A', level: 'Básica Superior' },
  { code: '03501', name: 'ASTUDILLO HURTADO DANNA PAOLA', course: '10 EGB A', level: 'Básica Superior' },
  { code: '02757', name: 'BACULIMA CHUNCHI MARTIN ANDRES', course: '10 EGB A', level: 'Básica Superior' },
  { code: '03160', name: 'BARRERA RAMÓN JOSE DAVID', course: '10 EGB A', level: 'Básica Superior' },
  { code: '02586', name: 'BRAVO BARRERA GABRIEL BENJAMIN', course: '10 EGB A', level: 'Básica Superior' },
  { code: '02762', name: 'CRESPO SILVA JOAQUIN', course: '10 EGB A', level: 'Básica Superior' },
  { code: '02583', name: 'GUTIÉRREZ SERRANO OLIVIA', course: '10 EGB A', level: 'Básica Superior' },
  { code: '02602', name: 'MONCAYO PIÑA EMILIO JAVIER', course: '10 EGB A', level: 'Básica Superior' },
  { code: '02614', name: 'MOREIRA JIMENEZ IVANNA', course: '10 EGB A', level: 'Básica Superior' },
  { code: '02601', name: 'ORELLANA BARROS MATEO NICOLAS', course: '10 EGB A', level: 'Básica Superior' },
  { code: '02573', name: 'OVIEDO BUITRÓN VICTORIA ALEJANDRA', course: '10 EGB A', level: 'Básica Superior' },
  { code: '02597', name: 'PERALTA OCHOA CARLOS JULIAN', course: '10 EGB A', level: 'Básica Superior' },
  { code: '02559', name: 'PEREZ SIGCHA MARTINA ALEJANDRA', course: '10 EGB A', level: 'Básica Superior' },
  { code: '03006', name: 'PURUNCAJAS CASTILLO FAVIO ESTEBAN', course: '10 EGB A', level: 'Básica Superior' },
  { code: '02577', name: 'ROJAS PESANTEZ DANNA ISABELLA', course: '10 EGB A', level: 'Básica Superior' },
  { code: '03747', name: 'SANCHEZ SACOTO BRIANNA VALESKA', course: '10 EGB A', level: 'Básica Superior' },
  { code: '02546', name: 'SIDDONS PINOS JULIAN', course: '10 EGB A', level: 'Básica Superior' },
  { code: '02552', name: 'TORRES VELETANGA ARIANA ISABELLA', course: '10 EGB A', level: 'Básica Superior' },
  { code: '03707', name: 'ULLOA MACHADO MANUELA', course: '10 EGB A', level: 'Básica Superior' },
  { code: '03497', name: 'VASCONEZ SUAREZ WILLIAM FELIPE', course: '10 EGB A', level: 'Básica Superior' },
  { code: '02575', name: 'VEGA AVILA NICOLAS ALEJANDRO', course: '10 EGB A', level: 'Básica Superior' },
  { code: '02581', name: 'VILLA MAXI EMILY ANALIZ', course: '10 EGB A', level: 'Básica Superior' },

  // 8 EGB B
  { code: '02734', name: 'ASTUDILLO ARAUJO JUAN DAVID', course: '8 EGB B', level: 'Básica Superior' },
  { code: '03724', name: 'AUQUI BERNAL JOAQUIN ALEJANDRO', course: '8 EGB B', level: 'Básica Superior' },
  { code: '02736', name: 'CABRERA BARBECHO MARIA JOSE', course: '8 EGB B', level: 'Básica Superior' },
  { code: '03030', name: 'CARDENAS ZAMBRANO JUAN CRISTOBAL', course: '8 EGB B', level: 'Básica Superior' },
  { code: '03055', name: 'CONTRERAS SAA MATIAS JOSE', course: '8 EGB B', level: 'Básica Superior' },
  { code: '03703', name: 'FAJARDO SAQUIPAY ARIANNA SALOME', course: '8 EGB B', level: 'Básica Superior' },
  { code: '02793', name: 'GALINDO ALEMAN AKANE', course: '8 EGB B', level: 'Básica Superior' },
  { code: '03022', name: 'GONZÁLEZ PRIETO LIONEL ANDRÉS', course: '8 EGB B', level: 'Básica Superior' },
  { code: '02907', name: 'GUZMAN ORDOÑEZ LUCRECIA ABISAAC', course: '8 EGB B', level: 'Básica Superior' },
  { code: '02795', name: 'MERCHAN CAJAMARCA MARTIN ALEXANDER', course: '8 EGB B', level: 'Básica Superior' },
  { code: '03722', name: 'MIELEWCZYK IGNACY', course: '8 EGB B', level: 'Básica Superior' },
  { code: '02884', name: 'ORTIZ BENITEZ ISABELLA', course: '8 EGB B', level: 'Básica Superior' },
  { code: '02741', name: 'PARRA CORDOVA CHRISTIAN ESTEBAN', course: '8 EGB B', level: 'Básica Superior' },
  { code: '02800', name: 'PAVON HERAS JAIME EDUARDO', course: '8 EGB B', level: 'Básica Superior' },
  { code: '02885', name: 'PESANTEZ TENEZACA TOMAS FRANCISCO', course: '8 EGB B', level: 'Básica Superior' },
  { code: '02784', name: 'ROJAS SANCHEZ THIAGO NICOLAS', course: '8 EGB B', level: 'Básica Superior' },
  { code: '02802', name: 'SEGOVIA MEJIA VALERIA ESTEFANIA', course: '8 EGB B', level: 'Básica Superior' },
  { code: '03702', name: 'TAPIA HERRERA CHRISTIAN JESUS', course: '8 EGB B', level: 'Básica Superior' },
  { code: '03591', name: 'VASCO VINTIMILLA ISABELLA', course: '8 EGB B', level: 'Básica Superior' },
  { code: '03345', name: 'VERDUGO RODRIGUEZ MARK ANTHONY', course: '8 EGB B', level: 'Básica Superior' },

  // 8 EGB A
  { code: '02733', name: 'ANDRADE CALDERON SOFIA BEATRIZ', course: '8 EGB A', level: 'Básica Superior' },
  { code: '02874', name: 'BARRERA AVILA EMILIO XAVIER', course: '8 EGB A', level: 'Básica Superior' },
  { code: '03312', name: 'BASTIDAS ULLAURI ALEJANDRA PAOLA', course: '8 EGB A', level: 'Básica Superior' },
  { code: '03039', name: 'BONILLA DURANGO RICARDO GABRIEL', course: '8 EGB A', level: 'Básica Superior' },
  { code: '03434', name: 'CRIOLLO SAMANIEGO ARIEL', course: '8 EGB A', level: 'Básica Superior' },
  { code: '03018', name: 'ESPINOZA SEMPÉRTEGUI SOPHIA ALEXANDRA', course: '8 EGB A', level: 'Básica Superior' },
  { code: '02864', name: 'GUTIÉRREZ SERRANO EZEQUIEL', course: '8 EGB A', level: 'Básica Superior' },
  { code: '02786', name: 'MEESTERBURRIE PRIETO TOMÁS JAN', course: '8 EGB A', level: 'Básica Superior' },
  { code: '02738', name: 'MOLINA VILLEGAS JULIO CESAR', course: '8 EGB A', level: 'Básica Superior' },
  { code: '02890', name: 'MOREIRA JIMENEZ ALONDRA', course: '8 EGB A', level: 'Básica Superior' },
  { code: '02894', name: 'MOSCOSO GOMEZ ANA PAULA', course: '8 EGB A', level: 'Básica Superior' },
  { code: '02799', name: 'OLMEDO BARRAGAN ETHAN SEBASTIAN', course: '8 EGB A', level: 'Básica Superior' },
  { code: '02740', name: 'ORTEGA PERALTA FRANCISCO ANDRES', course: '8 EGB A', level: 'Básica Superior' },
  { code: '02796', name: 'PIEDRA PIEDRA EMANUEL', course: '8 EGB A', level: 'Básica Superior' },
  { code: '02790', name: 'PILLACELA CAÑAFE BEVERLY BRIANNA', course: '8 EGB A', level: 'Básica Superior' },
  { code: '03481', name: 'RINCONES MOLINA GABRIEL ALEJANDRO', course: '8 EGB A', level: 'Básica Superior' },
  { code: '03066', name: 'RODRIGUEZ QUINDE JUAN DAVID', course: '8 EGB A', level: 'Básica Superior' },
  { code: '02809', name: 'SALGADO MOGROVEJO MATEO JOSUÉ', course: '8 EGB A', level: 'Básica Superior' },
  { code: '02789', name: 'SEMPERTEGUI BARRERA JOSE DAVID', course: '8 EGB A', level: 'Básica Superior' },
  { code: '03146', name: 'VASQUEZ PALACIOS JOSE MANUEL', course: '8 EGB A', level: 'Básica Superior' },
];
